---
name: Simple Java Test
author: Theis Jensen
description: Simple Java application for Green Metrics Tool testing

services:
  java-app:
    build: .
    container_name: primtalsberegningjava

flow:
  - name: Run prime calculation
    container: primtalsberegningjava
    commands:
      - type: console
        command: java Main 100
        note: Calculate primes up to 100
